name: Publish to NuGet

on:
  push:
    branches:
      - main
      - master # je nach Hauptbranch deines Repos
  workflow_dispatch: # Manuelles Triggern erlauben

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0' # oder deine Zielversion

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Pack NuGet package
      run: dotnet pack --configuration Release

    - name: Publish to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.DS_LIB_APIKEY }}
      run: dotnet nuget push **/bin/Release/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
